### ISSUE TITLE
Error while starting up 

### ISSUE THREAD

**Issue by fii** [kubespray/kargo-cli#69]
Are you sure to overwrite it ? [Y/n] y

CLONING KARGO GIT REPO *********************************************************
Cloning into '/home/fii/.kargo'...
kargo repo cloned
Traceback (most recent call last):
  File "/usr/bin/kargo", line 381, in <module>
    args.func(config)
  File "/usr/bin/kargo", line 49, in aws
    A.gen_ec2_playbook()
  File "/usr/lib/python2.7/site-packages/kargo/cloud.py", line 169, in gen_ec2_playbook
    k, v = kv.split("=")
AttributeError: 'dict' object has no attribute 'split'

**Comment by mandeepbal** [comment]
I'm getting the exact same issue when I start-up the docker container and run kargo for the first time.

```
root@277ba3ed28b1:/# kargo aws --nodes 3

CLONING KARGO GIT REPO *********************************************************
Cloning into '/root/.kargo'...
kargo repo cloned
Traceback (most recent call last):
  File "/usr/local/bin/kargo", line 381, in <module>
    args.func(config)
  File "/usr/local/bin/kargo", line 49, in aws
    A.gen_ec2_playbook()
  File "/usr/local/lib/python2.7/dist-packages/kargo/cloud.py", line 169, in gen_ec2_playbook
    k, v = kv.split("=")
AttributeError: 'dict' object has no attribute 'split'
```

this is what my kargo.yml file looks like:
```
kargo_git_repo: "https://github.com/kubespray/kargo.git"
# Logging options
loglevel: "debug"

# Amazon web services options
# ---
aws_access_key: "ŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻ"
aws_secret_key: "ŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻ"
key_name: "kubespray"
ami: "ami-kubespray" #Ubuntu Server 16.04 LTS (HVM), SSD Volume Type -
# masters_instance_type: "<masters_instance_type>"
# nodes_instance_type: "<nodes_instance_type>"
# etcds_instance_type: "<etcds_instance_type>"
masters_instance_profile_name: "kubespray"
nodes_instance_profile_name: "kubespray"
etcds_instance_profile_name: "kubespray"
security_group_name: "kubespray"
security_group_id: "sg-kubespray"
assign_public_ip: True
vpc_subnet_id: "vpc-kubespray"
region: "us-east-1"
tags:
  - type: kubespraykargo_git_repo: "https://github.com/kubespray/kargo.git"
# Logging options
loglevel: "debug"

# Amazon web services options
# ---
aws_access_key: "ŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻ"
aws_secret_key: "ŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻŻ"
key_name: "kubespray"
ami: "ami-kubespray" #Ubuntu Server 16.04 LTS (HVM), SSD Volume Type -
# masters_instance_type: "<masters_instance_type>"
# nodes_instance_type: "<nodes_instance_type>"
# etcds_instance_type: "<etcds_instance_type>"
masters_instance_profile_name: "kubespray"
nodes_instance_profile_name: "kubespray"
etcds_instance_profile_name: "kubespray"
security_group_name: "kubespray"
security_group_id: "sg-kubespray"
assign_public_ip: True
vpc_subnet_id: "vpc-kubespray"
region: "us-east-1"
tags:
  - type: kubespray
```
